Oro\Bundle\ProductBundle\Entity\Product:
    fields:
        # @deprecated Field "product_detail" will be removed in oro/google-tag-manager-bundle:5.1.0.
        -   name: product_detail
            type: text
            fulltext: false
        # Oro\Bundle\GoogleTagManagerBundle\EventListener\Analytics4\WebsiteSearchIndexerListener::PRODUCT_DETAIL_FIELD
        -   name: gtm_analytics4_product_detail
            type: text
            fulltext: false
