# @deprecated Will be removed in oro/google-tag-manager-bundle:5.1.0.

layout:
    actions:
        - '@setBlockTheme':
            themes: 'OroGoogleTagManagerBundle:layouts:blank/oro_frontend_root/product_list_gtm.html.twig'
        - '@add':
            id: featured_products_list_gtm
            parentId: featured_products_container
            blockType: block
            options:
                visible: '=data["featured_products"].getProducts() && data["oro_google_tag_manager_data_collection_state"].isEnabled("universal_analytics")'
        - '@add':
            id: new_arrivals_list_gtm
            parentId: new_arrival_products_container
            blockType: block
            options:
                visible: '=data["new_arrivals"].getProducts() && data["oro_google_tag_manager_data_collection_state"].isEnabled("universal_analytics")'
        - '@add':
            id: top_selling_list_gtm
            parentId: top_selling_items_container
            blockType: block
            options:
                visible: '=data["top_selling_items"].getProducts() && data["oro_google_tag_manager_data_collection_state"].isEnabled("universal_analytics")'
