dynamic-imports:
    commons:
        - orogoogletagmanager/js/app/components/data-layer-manager-component
        - orogoogletagmanager/js/app/components/data-layer-push-component
        - orogoogletagmanager/js/app/components/analytics4/data-layer-manager-analytics4-component
        - orogoogletagmanager/js/app/components/analytics4/image-slider-gtm-analytics4-component
        - orogoogletagmanager/js/app/components/analytics4/products-datagrid-gtm-analytics4-component
        - orogoogletagmanager/js/app/components/analytics4/products-embedded-list-gtm-analytics4-component
        - orogoogletagmanager/js/app/views/analytics4/product-gtm-analytics4-view
