services:
    oro_google_tag_manager.data_layer.manager:
        class: 'Oro\Bundle\GoogleTagManagerBundle\DataLayer\DataLayerManager'
        lazy: true
        arguments:
            - '@session'
            - !tagged_iterator oro_google_tag_manager.data_layer.collector

    oro_google_tag_manager.provider.google_tag_manager_settings:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\GoogleTagManagerSettingsProvider'
        arguments:
            - '@doctrine'
            - '@oro_config.manager'

    oro_google_tag_manager.provider.data_collection_state:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\DataCollectionStateProvider'
        arguments:
            - '@oro_google_tag_manager.provider.google_tag_manager_settings'
            - !tagged_iterator oro_google_tag_manager.data_collection_state_provider
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: oro_google_tag_manager }

    oro_google_tag_manager.provider.data_collection_state.config_based:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\DataCollectionStateConfigBasedProvider'
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: oro_google_tag_manager.data_collection_state_provider }

    oro_google_tag_manager.provider.analytics4.product_detail:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\Analytics4\ProductDetailProvider'
        arguments:
            - '@doctrine'

    oro_google_tag_manager.provider.analytics4.checkout_detail:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\Analytics4\Checkout\CheckoutDetailProvider'
        arguments:
            - '@oro_google_tag_manager.provider.analytics4.product_detail'
            - '@oro_pricing.provider.product_price'
            - '@oro_pricing.model.product_price_scope_criteria_factory'
            - '@oro_shipping.formatter.shipping_method_label'
            - '@oro_payment.formatter.payment_method_label'
            - '%oro_google_tag_manager.products.batch_size%'
        calls:
            - ['setProductPriceCriteriaFactory', ['@oro_pricing.product_price_criteria_factory']]
            - ['setCheckoutSubtotalProvider', ['@oro_checkout.provider.checkout_subtotal']]

    oro_google_tag_manager.provider.analytics4.purchase_detail:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\Analytics4\Checkout\PurchaseDetailProvider'
        arguments:
            - '@doctrine'
            - '@oro_google_tag_manager.provider.analytics4.product_detail'
            - '@oro_tax.provider.tax_provider_registry'
            - '@oro_google_tag_manager.provider.applied_promotions_names'
            - '@oro_shipping.formatter.shipping_method_label'
            - '@oro_payment.formatter.payment_method_label'
            - '%oro_google_tag_manager.products.batch_size%'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: oro_google_tag_manager }

    oro_google_tag_manager.provider.page_type:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\PageTypeProvider'
        arguments:
            - !tagged_iterator oro_google_tag_manager.page_type_guesser

    oro_google_tag_manager.page_type_guesser.by_request_route:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\PageType\PageTypeGuesserByRequestRoute'
        arguments:
            - '@request_stack'
            -
                oro_frontend_root: 'home'
                oro_product_frontend_product_index: 'category'
                oro_product_frontend_product_view: 'product'
                oro_shopping_list_frontend_view: 'basket'
                oro_shopping_list_frontend_update: 'basket'
                oro_sale_quote_frontend_view: 'basket'
                oro_checkout_frontend_checkout: 'checkout'
                oro_product_frontend_product_search: 'search'
        tags:
            - { name: oro_google_tag_manager.page_type_guesser, priority: 100 }

    oro_google_tag_manager.event_listener.analytics4.website_search_index:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\Analytics4\WebsiteSearchIndexerListener'
        arguments:
            - '@oro_website_search.manager.website_context_manager'
            - '@oro_google_tag_manager.provider.analytics4.product_detail'
        tags:
            - { name: kernel.event_listener, event: oro_website_search.event.index_entity.product, method: onWebsiteSearchIndex }

    oro_google_tag_manager.event_listener.analytics4.frontend_product_datagrid_product_detail:
        class: Oro\Bundle\GoogleTagManagerBundle\EventListener\Analytics4\ProductDatagridProductDetailListener
        arguments:
            - '@oro_google_tag_manager.provider.data_collection_state'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre.frontend-product-search-grid, method: onPreBuild }
            - { name: kernel.event_listener, event: oro_datagrid.search_datasource.result.after.frontend-product-search-grid, method: onResultAfter }

    oro_google_tag_manager.event_listener.analytics4.product_list.product_detail:
        class: Oro\Bundle\GoogleTagManagerBundle\EventListener\Analytics4\ProductListProductDetailListener
        arguments:
            - '@oro_google_tag_manager.provider.data_collection_state'
        tags:
            - { name: kernel.event_listener, event: oro_product.product_list.build_query, method: onBuildQuery }
            - { name: kernel.event_listener, event: oro_product.product_list.build_result, method: onBuildResult }

    oro_google_tag_manager.provider.product_price_detail:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\ProductPriceDetailProvider'
        public: false
        arguments:
            - '@security.token_storage'
            - '@oro_website.manager'
            - '@oro_pricing.user_currency_manager'
            - '@oro_pricing.provider.product_price'
            - '@oro_pricing.model.product_price_scope_criteria_factory'
        calls:
            - ['setProductPriceCriteriaFactory', ['@oro_pricing.product_price_criteria_factory']]

    oro_google_tag_manager.event_listener.analytics4.shopping_list_line_item:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\Analytics4\ShoppingListLineItemEventListener'
        arguments:
            - '@oro_frontend.request.frontend_helper'
            - '@oro_google_tag_manager.data_layer.manager'
            - '@oro_google_tag_manager.provider.analytics4.product_detail'
            - '@oro_google_tag_manager.provider.product_price_detail'
            - '@oro_google_tag_manager.provider.data_collection_state'
            - '%oro_google_tag_manager.products.batch_size%'
        calls:
            - [setProductLineItemCartHandler, ['@oro_google_tag_manager.data_layer.analytics4.product_line_item_cart_handler']]
        tags:
            - { name: kernel.event_listener, event: oro_checkout.checkout_source_entity_remove.before, method: onCheckoutSourceEntityClearOrRemove }
            - { name: kernel.event_listener, event: oro_checkout.checkout_source_entity_clear, method: onCheckoutSourceEntityClearOrRemove }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\ShoppingListBundle\Entity\LineItem', event: prePersist }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\ShoppingListBundle\Entity\LineItem', event: preUpdate }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\ShoppingListBundle\Entity\LineItem', event: preRemove }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onClear }

    oro_google_tag_manager.data_layer.analytics4.product_line_item_cart_handler:
        class: 'Oro\Bundle\GoogleTagManagerBundle\DataLayer\Analytics4\ProductLineItemCartHandler'
        shared: false
        arguments:
            - '@oro_google_tag_manager.data_layer.manager'
            - '@oro_google_tag_manager.provider.analytics4.product_detail'
            - '@oro_pricing.provider.product_line_item_price'
            - '@oro_pricing.user_currency_manager'
        calls:
            - [setBatchSize, ['%oro_google_tag_manager.products.batch_size%']]

    oro_google_tag_manager.event_listener.analytics4.checkout_purchase:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\Analytics4\CheckoutPurchaseEventListener'
        arguments:
            - '@oro_frontend.request.frontend_helper'
            - '@oro_google_tag_manager.provider.data_collection_state'
            - '@oro_google_tag_manager.data_layer.manager'
            - '@oro_google_tag_manager.provider.analytics4.purchase_detail'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\CheckoutBundle\Entity\Checkout', event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onClear }

    oro_google_tag_manager.event_listener.analytics.checkout_info:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\Analytics4\CheckoutInfoEventListener'
        arguments:
            - '@oro_frontend.request.frontend_helper'
            - '@oro_google_tag_manager.provider.data_collection_state'
            - '@oro_google_tag_manager.data_layer.manager'
            - '@oro_google_tag_manager.provider.analytics4.checkout_detail'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\CheckoutBundle\Entity\Checkout', event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onClear }

    oro_google_tag_manager.event_listener.analytics.begin_checkout:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\Analytics4\BeginCheckoutEventListener'
        arguments:
            - '@oro_frontend.request.frontend_helper'
            - '@oro_google_tag_manager.provider.data_collection_state'
            - '@oro_google_tag_manager.data_layer.manager'
            - '@oro_google_tag_manager.provider.analytics4.checkout_detail'
        tags:
            - { name: kernel.event_listener, event: extendable_condition.start_checkout, method: onStartCheckout }

    oro_google_tag_manager.event_listener.analytics4.request_product_item:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\Analytics4\RequestProductItemEventListener'
        arguments:
            - '@oro_frontend.request.frontend_helper'
            - '@oro_google_tag_manager.data_layer.manager'
            - '@oro_google_tag_manager.provider.analytics4.product_detail'
            - '@oro_google_tag_manager.provider.product_price_detail'
            - '@oro_google_tag_manager.provider.data_collection_state'
            - '%oro_google_tag_manager.products.batch_size%'
        calls:
            - [setProductLineItemCartHandler, ['@oro_google_tag_manager.data_layer.analytics4.product_line_item_cart_handler']]
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\RFPBundle\Entity\RequestProductItem', event: prePersist }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onClear }

    oro_google_tag_manager.provider.applied_promotions_names:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\AppliedPromotionsNamesProvider'
        arguments:
            - '@doctrine'
            - '@oro_promotion.provider.entity_coupons_provider'
