services:
    oro_google_tag_manager.data_layer.manager:
        class: 'Oro\Bundle\GoogleTagManagerBundle\DataLayer\DataLayerManager'
        public: false
        arguments:
            - '@session'
            - !tagged_iterator oro_google_tag_manager.data_layer.collector

    oro_google_tag_manager.provider.google_tag_manager_settings:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\GoogleTagManagerSettingsProvider'
        public: false
        arguments:
            - '@doctrine'
            - '@oro_config.manager'

    oro_google_tag_manager.provider.product_detail:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\ProductDetailProvider'
        public: false
        arguments:
            - '@oro_entity.doctrine_helper'

    oro_google_tag_manager.provider.checkout_step:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\Checkout\CheckoutStepProvider'
        public: false
        arguments:
            - '@oro_workflow.manager'
            - ['enter_credentials_step', 'customer_consents']

    oro_google_tag_manager.provider.checkout_detail:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\Checkout\CheckoutDetailProvider'
        public: false
        arguments:
            - '@oro_google_tag_manager.provider.product_detail'
            - '@oro_google_tag_manager.provider.checkout_step'
            - '@oro_pricing.provider.product_price'
            - '@oro_pricing.model.product_price_scope_criteria_factory'
            - '%oro_google_tag_manager.products.batch_size%'

    oro_google_tag_manager.provider.purchase_detail:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\Checkout\PurchaseDetailProvider'
        public: false
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_google_tag_manager.provider.product_detail'
            - '@oro_tax.provider.tax_provider_registry'
            - '@oro_promotion.provider.entity_coupons_provider'
            - '@oro_shipping.formatter.shipping_method_label'
            - '@oro_payment.formatter.payment_method_label'
            - '%oro_google_tag_manager.products.batch_size%'

    oro_google_tag_manager.provider.page_type:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\PageTypeProvider'
        public: false
        arguments:
            - !tagged_iterator oro_google_tag_manager.page_type_guesser

    oro_google_tag_manager.page_type_guesser.by_request_route:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\PageType\PageTypeGuesserByRequestRoute'
        public: false
        arguments:
            - '@request_stack'
            -
                oro_frontend_root': 'home'
                oro_product_frontend_product_index: 'category'
                oro_product_frontend_product_view: 'product'
                oro_shopping_list_frontend_view: 'basket'
                oro_shopping_list_frontend_update: 'basket'
                oro_sale_quote_frontend_view: 'basket'
                oro_checkout_frontend_checkout: 'checkout'
                oro_product_frontend_product_search: 'search'
        tags:
            - { name: oro_google_tag_manager.page_type_guesser, priority: 100 }

    oro_google_tag_manager.event_listener.website_search_index:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\WebsiteSearchIndexerListener'
        public: false
        arguments:
            - '@oro_website_search.manager.website_context_manager'
            - '@oro_google_tag_manager.provider.product_detail'
        tags:
            - { name: kernel.event_listener, event: oro_website_search.event.index_entity.product, method: onWebsiteSearchIndex }

    oro_google_tag_manager.event_listener.frontend_product_datagrid:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\FrontendProductDatagridListener'
        public: false
        arguments:
            - '@oro_google_tag_manager.provider.google_tag_manager_settings'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre.frontend-product-search-grid, method: onPreBuild }
            - { name: kernel.event_listener, event: oro_datagrid.search_datasource.result.after.frontend-product-search-grid, method: onResultAfter }

    oro_google_tag_manager.provider.product_price_detail:
        class: 'Oro\Bundle\GoogleTagManagerBundle\Provider\ProductPriceDetailProvider'
        public: false
        arguments:
            - '@security.token_storage'
            - '@oro_website.manager'
            - '@oro_pricing.user_currency_manager'
            - '@oro_pricing.provider.product_price'
            - '@oro_pricing.model.product_price_scope_criteria_factory'

    oro_google_tag_manager.event_listener.shopping_list_line_item:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\ShoppingListLineItemEventListener'
        public: false
        arguments:
            - '@oro_frontend.request.frontend_helper'
            - '@oro_google_tag_manager.data_layer.manager'
            - '@oro_google_tag_manager.provider.product_detail'
            - '@oro_google_tag_manager.provider.product_price_detail'
            - '@oro_google_tag_manager.provider.google_tag_manager_settings'
            - '%oro_google_tag_manager.products.batch_size%'
        tags:
            - { name: kernel.event_listener, event: oro_checkout.checkout_source_entity_remove.before, method: addShoppingListIdToIgnore }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\ShoppingListBundle\Entity\LineItem', event: prePersist }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\ShoppingListBundle\Entity\LineItem', event: preUpdate }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\ShoppingListBundle\Entity\LineItem', event: preRemove }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onClear }

    oro_google_tag_manager.event_listener.checkout:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\CheckoutEventListener'
        public: false
        arguments:
            - '@oro_frontend.request.frontend_helper'
            - '@oro_google_tag_manager.data_layer.manager'
            - '@oro_google_tag_manager.provider.purchase_detail'
            - '@oro_google_tag_manager.provider.google_tag_manager_settings'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\CheckoutBundle\Entity\Checkout', event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onClear }

    oro_google_tag_manager.event_listener.request_product_item:
        class: 'Oro\Bundle\GoogleTagManagerBundle\EventListener\RequestProductItemEventListener'
        public: false
        arguments:
            - '@oro_frontend.request.frontend_helper'
            - '@oro_google_tag_manager.data_layer.manager'
            - '@oro_google_tag_manager.provider.product_detail'
            - '@oro_google_tag_manager.provider.product_price_detail'
            - '@oro_google_tag_manager.provider.google_tag_manager_settings'
            - '%oro_google_tag_manager.products.batch_size%'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\RFPBundle\Entity\RequestProductItem', event: prePersist }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onClear }
